#!/bin/bash

if [ -z "$1" ]; then
    echo "请提供要备份的文件名"
    exit 1
fi

if [ ! -f "$1" ]; then
    echo "文件 $1 不存在"
    exit 1
fi

current_time=$(date +%Y-%m-%dT%H:%M:%S)
filename="$1"
backup_filename="$filename.bak_$current_time"

cp -f "$1" "$backup_filename"

ls -l